version: '3.8'

services:
  # app:
  #   image: your_golang_app_image  # Replace with your actual image name
  #   container_name: golang_app
  #   ports:
  #     - "${PORT}:${PORT}"
  #   environment:
  #     - ENV=${ENV}
  #     - PORT=${PORT}
  #     - SSL=${SSL}
  #     - API_VERSION=${API_VERSION}
  #     - DB_USER=${DB_USER}
  #     - DB_PASS=${DB_PASS}
  #     - DB_NAME=${DB_NAME}
  #     - ACCESS_SECRET=${ACCESS_SECRET}
  #     - REFRESH_SECRET=${REFRESH_SECRET}
  #     - REDIS_SECRET=${REDIS_SECRET}
  #     - REDIS_HOST=redis:6379  # Connects to the Redis service defined below
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   depends_on:
  #     - db
  #     - redis

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  pgdata:
